// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5SdfcScTkh2TflwbW25356YBY5x5aYng',
    appId: '1:659775075600:web:cafa35a8ab706364cbe195',
    messagingSenderId: '659775075600',
    projectId: 'crypto-app-cb831',
    authDomain: 'crypto-app-cb831.firebaseapp.com',
    storageBucket: 'crypto-app-cb831.appspot.com',
    measurementId: 'G-V5EXGF36JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMkS-GrhI-MbJd3fGBvrV1Iyq_ta9RtB8',
    appId: '1:659775075600:android:55a1c637942b1b81cbe195',
    messagingSenderId: '659775075600',
    projectId: 'crypto-app-cb831',
    storageBucket: 'crypto-app-cb831.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFeDaj2tRfUlJjP-5Eo-DB71nm6buVv3A',
    appId: '1:659775075600:ios:6ecc04e48f70c30dcbe195',
    messagingSenderId: '659775075600',
    projectId: 'crypto-app-cb831',
    storageBucket: 'crypto-app-cb831.appspot.com',
    iosBundleId: 'com.example.rateCrypto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFeDaj2tRfUlJjP-5Eo-DB71nm6buVv3A',
    appId: '1:659775075600:ios:6ecc04e48f70c30dcbe195',
    messagingSenderId: '659775075600',
    projectId: 'crypto-app-cb831',
    storageBucket: 'crypto-app-cb831.appspot.com',
    iosBundleId: 'com.example.rateCrypto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5SdfcScTkh2TflwbW25356YBY5x5aYng',
    appId: '1:659775075600:web:f61cc7fcab988a5dcbe195',
    messagingSenderId: '659775075600',
    projectId: 'crypto-app-cb831',
    authDomain: 'crypto-app-cb831.firebaseapp.com',
    storageBucket: 'crypto-app-cb831.appspot.com',
    measurementId: 'G-L87R9G4GKM',
  );
}
